apiVersion: v1
kind: Service
metadata:
  name: CRUD-application-service
spec:
  selector:
    app: CRUD-application
  ports:
  - protocol: TCP
    targetPort: 8081
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
