version: '3.8'

services:
  mongo_db:
    container_name: "database_container"
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - MONGODB_URI=mongodb://mongo_db:27017/Assignment_CRUD_APP
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
